# Generated by Django 3.1.6 on 2021-02-08 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('rows', models.IntegerField(blank=True, default=0)),
                ('items', models.TextField(blank=True, default='')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
