version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
  web:
    restart: always
    environment: 
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - .:/www/app
    image: apifirst
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db